[package]
name = "gsuite"
version = "0.1.0"
authors = ["Jess Frazelle <acidburn@jessfraz.com>"]
edition = "2018"

[dependencies]
cio = { path = "../cio" }
rand = "0.7"
reqwest = { version = "0.10", features = ["blocking", "json"] }
serde = { version = "1.0", features = ["derive"] }
yup-oauth2 = "3.1"
