[package]
name = "sendgrid"
version = "0.1.0"
authors = ["Jess Frazelle <acidburn@jessfraz.com>"]
edition = "2018"

[dependencies]
chrono = "0.4"
data-encoding = "2"
gsuite = { path = "../gsuite" }
reqwest = { version = "0.10", features = ["blocking", "json"] }
serde = { version = "1.0", features = ["derive"] }
