[workspace]
members = [
	"airtable",
	"barcodey",
	"checkr",
	"cfcert",
	"cio",
	"docusign",
	"drive",
	"giphy",
	"gsuite",
	"google-geocode",
	"gusto",
	"macros",
	"okta",
	"printy",
	"ramp",
	"revai",
	"sendgrid",
	"sheets",
	"shippo",
	"slack",
	"tailscale",
	"webhooky",
	"zoom",
]
