[workspace]
members = [
	"airtable",
	"cio",
	"drive",
	"giphy",
	"gsuite",
	"google-geocode",
	"gusto",
	"macros",
	"printy",
	"revai",
	"sendgrid",
	"sheets",
	"shippo",
	"slack",
	"tailscale",
	"webhooky",
	"zoom",
]
