[package]
name = "drive"
version = "0.1.0"
authors = ["Jess Frazelle <acidburn@jessfraz.com>"]
edition = "2018"

[dependencies]
reqwest = { version = "0.10", features = ["json"] }
serde = { version = "1.0", features = ["derive"] }
yup-oauth2 = "4.1"
