[package]
name = "printy"
description = "A simple server for listening on requests to print."
version = "0.1.0"
authors = ["Jess Frazelle <jess@oxide.computer>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cio-api = { path = "../cio" }
dropshot = "^0.5.0"
http = "0.2.0"
reqwest = "^0.11"
sentry = { version = "^0.23.0", features = ["anyhow"] }
tokio = { version = "1", features = ["full"] }
uuid = { version = "^0.8.1", features = ["serde", "v4"] }
