[package]
name = "webhooky"
description = "A simple webhook server for listening on GitHub and Google Sheets webhooks to perform events."
version = "0.1.0"
authors = ["Jess Frazelle <jess@oxide.computer>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
checkr = "^0.0.10"
chrono = { version = "0.4", features = ["serde"] }
chrono-humanize = "0.0.11"
cio-api = { git = "https://github.com/oxidecomputer/cio", branch = "master" }
#cio-api = { path = "../cio" }
docusign = "^0.1.0"
diesel = { version = "^1.4.6", features = ["serde_json", "postgres", "chrono", "128-column-tables", "r2d2"] }
#dropshot = "^0.5.0"
dropshot = { git = "https://github.com/oxidecomputer/dropshot", branch = "main" }
formdata = "^0.13.0"
futures-util = "0.3"
google-drive = "^0.1.23"
gusto-api = "^0.2.4"
#gusto-api = { path = "../../third-party-api-clients/gusto" }
http = "0.2.0"
hyper = { version = "0.10" }
mailchimp-api = "^0.1.11"
mime_guess = "2"
octorust = { version = "^0.1.16", features = ["httpcache"] }
quickbooks = "^0.1.12"
ramp-api = "^0.2.2"
#ramp-api = { path = "../../third-party-api-clients/ramp" }
rand = "^0.8.4"
regex = "^1.5.4"
schemars = { version = "0.8", features = ["chrono", "uuid"] }
sentry = "^0.22.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_qs = "0.8"
serde_urlencoded = "^0.7.0"
sheets = "^0.1.0"
shippo = "^0.1.12"
slack-chat-api = "^0.1.16"
tokio = { version = "1", features = ["full"] }
zoom-api = "^0.2.0"
#zoom-api = { path = "../../third-party-api-clients/zoom" }
