[package]
name = "webhooky"
description = "A simple webhook server for listening on GitHub and Google Sheets webhooks to perform events."
version = "0.1.0"
authors = ["Jess Frazelle <jess@oxide.computer>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
checkr = "^0.0.10"
chrono = { version = "0.4", features = ["serde"] }
chrono-humanize = "0.0.11"
cio-api = { git = "https://github.com/oxidecomputer/cio", branch = "master" }
#cio-api = { path = "../cio" }
docusign = "^0.1.0"
diesel = { version = "^1.4.6", features = ["serde_json", "postgres", "chrono", "128-column-tables", "r2d2"] }
#dropshot = "^0.5.0"
dropshot = { git = "https://github.com/oxidecomputer/dropshot", branch = "main" }
formdata = "^0.13.0"
futures-util = "0.3"
google-drive = "^0.1.0"
gusto-api = "^0.1.0"
http = "0.2.0"
#hubcaps = { version = "0.6", features = ["httpcache"] }
hubcaps = { git = "https://github.com/jessfraz/hubcaps", branch = "actions", features = ["httpcache"] }
hyper = { version = "0.10" }
#influxdb = { version = "0.3.0", features = ["derive"] }
influxdb = { git = "https://github.com/jessfraz/influxdb-rust", branch = "cloud", features = ["derive"] }
mailchimp-api = "^0.1.0"
quickbooks = "^0.1.0"
ramp-api = "^0.1.1"
regex = "^1.5.4"
schemars = { version = "0.8", features = ["chrono", "uuid"] }
sentry = "^0.22.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_qs = "0.8"
sheets = "^0.1.0"
shippo = "^0.1.12"
tokio = { version = "1", features = ["full"] }
