[package]
name = "cio-api"
description = "Helper functions and types for doing the activities of a CIO"
version = "0.1.2"
authors = ["Jess Frazelle <jess@oxide.computer>"]
edition = "2018"
license = "Apache-2.0"
repository = "https://github.com/oxidecomputer/cio"
documentation = "https://docs.rs/cio-api"

[dependencies]
airtable-api = "^0.1.0"
chrono = "0.4"
chrono-humanize = "0.0.11"
clap = {version = "2", features = ["yaml"]}
csv = "1.1"
google-drive = "^0.1.0"
html2text = "0.1"
#hubcaps = { version = "0.6.0", features = ["httpcache"] }
hubcaps = { git = "https://github.com/softprops/hubcaps", rev = "2385b8e957bb921f61c1146f075ae132dac5e95d" , features = ["httpcache"] }
pandoc = "0.8"
phonenumber = "0.2"
regex = "1"
reqwest = { version = "0.10", features = ["json"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
sheets = "^0.1.0"
toml = "0.5"
yup-oauth2 = "^4.1.2"
