[package]
name = "cio-api"
description = "Helper functions and types for doing the activities of a CIO"
version = "0.1.2"
authors = ["Jess Frazelle <jess@oxide.computer>"]
edition = "2018"
license = "Apache-2.0"
repository = "https://github.com/oxidecomputer/cio"
documentation = "https://docs.rs/cio-api"

[dependencies]
airtable-api = "^0.1.0"
chrono = "0.4"
chrono-humanize = "0.0.11"
google-drive = "^0.1.0"
html2text = "0.1"
pandoc = "0.8"
regex = "1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
