on:
  push:
    paths:
      - "src/**" # Only run on changes to the src directory.
      - ".github/workflows/cargo-test.yml" # Run when this file changes.
  pull_request:
    paths:
      - "src/**" # Only run on changes to the src directory.
      - ".github/workflows/cargo-test.yml" # Run when this file changes.
name: cargo test
jobs:
  cargotest:
    name: cargo test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: cargo test
        uses: docker://rust:latest
        with:
          entrypoint: cargo
          args: test
