on:
  schedule:
    - cron: "*/10 * * * *"
  push:
    branches:
      - master # Push events on master branch
    paths:
      - "configs/**" # Only run on changes to the configs directory.
      - ".github/workflows/run-airtable.yml" # Run when this file changes.
name: Run airtable
jobs:
  runAirtable:
    name: Run airtable
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Install latest nightly
        uses: actions-rs/toolchain@v1
        with:
            toolchain: nightly
            override: true
            components: rustfmt, clippy
      - name: Cache cargo registry
        uses: actions/cache@v1
        with:
          path: ~/.cargo/registry
          key: ${{ runner.os }}-cargo-registry-${{ hashFiles('**/Cargo.lock') }}
      - name: Cache cargo index
        uses: actions/cache@v1
        with:
          path: ~/.cargo/git
          key: ${{ runner.os }}-cargo-index-${{ hashFiles('**/Cargo.lock') }}
      - name: Cache cargo build
        uses: actions/cache@v1
        with:
          path: target
          key: ${{ runner.os }}-cargo-build-target-${{ hashFiles('**/Cargo.lock') }}
      - name: Run airtable
        run: make airtable
        shell: bash
        env:
          GITHUB_TOKEN: ${{ secrets.GADMIN_GITHUB_TOKEN }}
          GITHUB_ORG: oxidecomputer
          AIRTABLE_API_KEY: ${{ secrets.AIRTABLE_API_KEY }}
          AIRTABLE_BASE_ID: ${{ secrets.AIRTABLE_BASE_ID }}
          RUST_BACKTRACE : 1
      - name: Commit changes
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add .cache
          git commit -m "Run 'make airtable' and .cache/github" || echo "Nothing to commit"
      - name: Rebase
        run: |
          git remote set-url origin https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
          git fetch --unshallow origin
          git rebase origin/master || true
      - name: Push Changes to GitHub
        run: |
          git push origin master || true
