on:
  push:
    branches:
      - master # Push events on master branch
name: Run gadmin
jobs:
  runGadmin:
    name: Run gadmin
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Download gadmin
        run: make download-gadmin
      - name: Set up environment
        shell: bash
        run: |
          echo "$GSUITE_KEY" > ${{ github.workspace }}/gsuite_key
        env:
          GSUITE_KEY: ${{ secrets.GSUITE_KEY }}
      - name: Run gadmin
        run: make gadmin
        shell: bash
        env:
          GADMIN_CREDENTIAL_FILE: ${{ github.workspace }}/gsuite_key
          GADMIN_SUBJECT: ${{ secrets.GADMIN_SUBJECT }}
          GADMIN_ACCOUNT_ID: ${{ secrets.GADMIN_ACCOUNT_ID }}
          GITHUB_TOKEN: ${{ secrets.GADMIN_GITHUB_TOKEN }}
          GITHUB_ORG: oxidecomputer
          SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }}
          ZOOM_API_KEY: ${{ secrets.ZOOM_API_KEY }}
          ZOOM_API_SECRET: ${{ secrets.ZOOM_API_SECRET }}
      - name: Commit changes to directory
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add directory
          git commit -m "Run gadmin to update directory files" || echo "Nothing to commit"
      - name: Rebase
        run: |
          git rebase https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
      - name: Push Changes
        run: |
          git push https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git HEAD:master
