on:
  push:
    paths-ignore:
    - '.cache/**'
  pull_request:
    paths-ignore:
    - '.cache/**'
name: Shellcheck
jobs:
  runShellcheck:
    name: Run shellcheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Run shellcheck
        run: make shellcheck
        shell: bash
